CREATE OR REPLACE FILE FORMAT parquet_file_format
  TYPE = 'PARQUET'
  COMPRESSION = 'AUTO'
  RECORD_DELIMITER = '\n' 
  SKIP_HEADER = 0
  FIELD_OPTIONALLY_ENCLOSED_BY = ''
  NULL_IF = ()
  FIELD_OPTIONALLY_ENCLOSED_BY = ''
  DATE_FORMAT = 'AUTO'
  TIME_FORMAT = 'AUTO'
  TIMESTAMP_FORMAT = 'AUTO'
  BINARY_FORMAT = 'HEX';
